INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1340, '制造商导入', NULL, 1246, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:manufacturers:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1341, '供应商导入', NULL, 1252, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:suppliers:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1342, '物理位置导入', NULL, 1264, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:locations:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1343, '设备导入', NULL, 1277, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:device:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1345, '配件导入', NULL, 1283, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:accessories:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1346, '耗材导入', NULL, 1289, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:consumables:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1347, '软件导入', NULL, 1295, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:licenses:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1348, '服务导入', NULL, 1301, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:offering:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');
INSERT INTO `sys_menu` (`id`, `menu_name`, `lang_key`, `parent_id`, `order_num`, `path`, `component`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1350, '型号导入', NULL, 1319, 6, '#', '', 1, 0, 'F', '0', '0', 'itam:models:import', '#', 1, '2026-01-31 22:45:00', NULL, NULL, '');


ALTER TABLE `itam_offering` 
DROP COLUMN `target_type`,
DROP COLUMN `target_id`;